### ISSUE TITLE
车辆的yaw是车辆绕自身坐标系的航向角吗？

### ISSUE THREAD

**Issue by fanDongHust** [little-bookworm/TransparentChassisCuda#3]
get_warpaffine里bev_center_y - 12这句 -12是啥原因？

如果车辆的yaw是0，效果还可以；但是如果车辆的yaw不是0，发现效果就不佳！你那边用实车数据测试的时候，车辆的yaw不是0时，效果如何呢？

车辆的yaw是车辆绕自身坐标系的航向角吗？

**Comment by little-bookworm** [comment]
-12是对拼接原点位置的调整，因为拼接有误差，当yaw不为0时，拼接原点位置影响会很大，你可以根据拼接效果调整下这个值

**Comment by fanDongHust** [comment]
感谢回复！问题已经解决了的哈！
